# Generated by Django 3.1.3 on 2021-02-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0005_remove_lineitem_line_topping'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='toppings',
            field=models.ManyToManyField(blank=True, null=True, to='pizza_app.Topping'),
        ),
        migrations.AddField(
            model_name='topping',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
