# Generated by Django 3.1.3 on 2021-02-15 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0006_auto_20210215_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='quantity',
        ),
    ]
