# Generated by Django 3.1.3 on 2021-02-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0008_auto_20210216_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='pizza_app.Topping'),
        ),
    ]
